name: tests
on:
  - push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Velociraptor
        run: deno install -qA -n vr https://deno.land/x/velociraptor@$VERSION/cli.ts
        env:
          VERSION: 1.0.0-beta.17
      - name: Run tests
        run: >
          vr test-cov
      - name: Upload coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./cov.lcov
