name: Test
on:
  - push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: deno test
