name: tests
on:
  - push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Run tests
        run: deno test --coverage=./cov --unstable --allow-run
      - name: Generate lcov
        run: deno coverage --unstable --lcov ./cov > cov.lcov
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          files: cov.lcov
