name: tests
on:
  - push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Run tests
        run: deno test --coverage=./cov --unstable --allow-run
      - name: Generate lcov
        run: deno coverage --unstable --lcov ./cov > cov.lcov
      - name: Upload coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./cov.lcov
